project:
  type: website

website:
  title: "Testing Exercise functionality"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - quarto-live_web.qmd
      - example.qmd
      - dynamic.qmd

format:
  html:
    theme: cosmo
    css: styles/website.css
    toc: true